<%@ page language="java" contentType="text/html; charset=UTF-8"
    pageEncoding="UTF-8"%>
<jsp:include page="header.jsp"/>
<body class="page no-sidebar header-style-1 menu-has-search menu-has-cart">

<div id="featured-title" class="clearfix featured-title-left">
    <div id="featured-title-inner" class="container clearfix">
        <div class="featured-title-inner-wrap">
            <div class="featured-title-heading-wrap">
                <h1 class="featured-title-heading">Ajouter Pack</h1>
            </div>
            <div id="breadcrumbs">
                <div class="breadcrumbs-inner">
                    <div class="breadcrumb-trail">
                        <a href="#" title="Construction" rel="home" class="trail-begin">Home</a>
                        <span class="sep">/</span>
                        <span class="trail-end">Ajouter Pack</span>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<br>

<div class="wrapper">
    <div class="main">
        <div class="section">
            <div class="container">   
                <form action="AjouterPack" method="post" enctype="multipart/form-data">
                    <div class="row">
                        <div class="col-md-5 col-sm-5">
                            <h6>Image du pack *</h6>
                            <div class="fileinput fileinput-new text-center" data-provides="fileinput">
                              <div class="fileinput-new thumbnail img-no-padding" style="max-width: 370px; max-height: 250px;">
                                <img src="assets/img/image_produit.jpg" alt="...">
                              </div>
                              <div class="fileinput-preview fileinput-exists thumbnail img-no-padding" style="max-width: 370px; max-height: 250px;"></div>
                              <div>
                              <br>
                                <span class="wprt-button outline dark small btn-file"><span class="fileinput-new">sélectionner une image</span><span class="fileinput-exists">Changer</span>
                                <input type="file" name="image" required></span>
                                <a href="#" class="wprt-button small fileinput-exists" data-dismiss="fileinput"><i class="fa fa-times"></i> Supprimer</a>
                              </div>
                            </div>
                            <br> <br>

		                    	<div class="row price-row">
                                <div class="col-md-6">
                                    <h6>Prix *</h6>
                                    <div>
                                        <input type="number" value="" placeholder="Entrer le prix" name="prix" required>              
                                    </div>
                                </div>
                            </div>
                            <br>

                        </div>

                        <div class="col-md-7 col-sm-7">
                            <div class="form-group">
                                <h6>Nom du produit *</h6>
                                <input type="text" placeholder="Entrer le nom du produit ici..." name="nomProduit" required>
                            </div>
                            
                            <div class="form-group">
                                <h6>Description *</h6>
								<textarea placeholder="Entrer une bref description sur le produit ici..." rows="13" name="descriptionProduit" required ></textarea>
                            </div>	

                        </div>
                    </div>
    
			  <table id="autoGeneratedID" role="grid" class="table table-striped table-bordered">
			    <thead>
			      <tr>
			        <th id="first_name" role="gridcell">image</th>
			        <th id="last_name" role="gridcell">Nom</th>
			        <th id="user_role" role="gridcell">Categorie</th>
			        <th role="gridcell" id="user_actions">Sous Categorie</th>
			        <th role="gridcell" id="user_actions">Ajout au Réferences</th>
			      </tr>
			    </thead>
			    <tbody>
			 
			 		<c:forEach var="produit" items="${ produits }">
			 			<tr>
					        <td id="image_prod" role="gridcell"><div class="product-thumbnail"><img style="max-height: 10em; max-width: 10em;" src="http://localhost:8080/images/${ produit.image }"></div></td>
					        <td id="nom_prod" role="gridcell"><a href="ProduitSingle?id=${produit.id}" target="_blank">${ produit.nom }</a></td>
					        <td id="categorie_prod" role="gridcell">${ produit.categorie }</td>
					        <td id="sousCategorie_prod" role="gridcell">${ produit.sousCategorie }</td>
					        <td id="check_prod" role="gridcell"> <input type="button" onclick="check(this, '${produit.id}');" value="Add"/> </td>
					      </tr>
			 		</c:forEach>
			 		
			    <tbody>
			  </table>
			  
				    <div class="col-md-4">
                       <button class="wprt-button dark" name="...">Annuler </button>
                	</div>
                    <div class="col-md-8">  
                       <button class="wprt-button outline" name="...">Enregister </button>
                    </div>

                </form>
                
                <br>
            </div>
        </div>
    </div>
</div>
<br>

</body>

<script type="text/javascript">
function check(btn, vale) {
	  if (btn.value === 'Add') {
	    btn.value = 'Suppr';
	    $('<input>').attr({
	        type: 'hidden',
	        id: 'ref',
	        name: 'ref',
	        value: vale
	    }).appendTo('form');
	  } 
	  else if (btn.value === 'Suppr') {
	    btn.value = 'Add';
	    $('input[type=hidden]').each(function() {
	    	var vv = $(this).val();
	    	  if(vv == vale)
	    	  {
	    		  $(this).remove();
	    	  }
	    	});
	  }
	}
</script>

<jsp:include page="footer.jsp"/>